language: node_js

# build matrix
os:
  - linux
  - osx
node_js:
  - 6
  - 7
compiler:
  - gcc
env:
  global:
    - CXX=g++-4.8
  matrix:
    - REQUIRED_TESTS=true
    - OPTIONAL_TESTS=true

# allow the ecosystem tests to fail. these failures should be
# communicated to the maintainers of the failing modules
matrix:
  allow_failures:
    - env: OPTIONAL_TESTS=true
  fast_finish: true

# gcc 4.8 is included on osx
# install gcc 4.8 on linux using apt
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

before_script:
- npm link

script:
- npm test

# retry the ecosystem tests if required; occasionally a no-output-received timeout will occur
# see: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
- 'if [ ${REQUIRED_TESTS} = "true" ]; then
    travis_retry npm run ci;
  fi'

- 'if [ ${OPTIONAL_TESTS} = "true" ]; then
    npm run ci;
  fi'

after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info

notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/54f8a1e753f859f5ca1a
    on_start: never
    on_failure: change

deploy:
  provider: npm
  email: hello@trailsjs.io
  api_key:
    secure: d/VChdWWPr8Mi6UyRUjIhjEfXHoyTCJ0z/pyNzF3yd2vpvC07fK90ka0CPxHhKyPWj7h7+ZG0FO0U8wj4YAZ8QeKIuc5rZbe1wI5yISpbnVxDKk0tYqyDFCRbmXVu7RNeLbBPN6y3fbJYdCLM14ugTfaJaBdewVTeOFGFBA712vHwu8ptWW/zw72YbH9d6C+LnAyz17ZyeAG7BvABISKv+bzuYexFaw4gv/uGNp2o//zC4FlXNcVWR3hb/cS6SWWoiPdsOZvDJTY+2J+WSEMlZ+PIZaJjfki4RbisoIg5Q3KM/WhgXwRfgma4POrGSqXvg8Yy1lqTIoZJT1SEnIj+KIOHuLoI+Rv1hc3n+Aw5Q2iMSPo/QlbolhfOhmGRkx5XIxIlKs/Vf6GJGQBf2lB5W2tgdf3UYwGbXjWOUoj+4NBotWQ4vaHlwfJb9sm66yXG9ayDkgc8Gegj6ooRC+xl8irgu/xgtSMKek6I893r/sLTnAkYcrLMUSqOp9qMBk8Zfdir978yKx4pTPBJvlnilze+cdSNMSXokKMDNF4wbaDVCyaFsoYEYNW/basaKynBiPgi4exjWH1SlXBOKA+LTr8i9ZwdGNIRDx3mxTiUHvwaYbn9tHOt8ymEwTfFe90a2XDp0+sUKEtLT+i6jF41iFQq0b/OwzWnQf3GfcDyYY=
  on:
    tags: true
    repo: trailsjs/trails
    node: 6
