environment:
  compiler: gcc-4.8.4-posix

  matrix:
  - nodejs_version: "4"
    REQUIRED_TESTS: "true"
  - nodejs_version: "4"
    OPTIONAL_TESTS: "true"
  - nodejs_version: "5"
    REQUIRED_TESTS: "true"
  - nodejs_version: "5"
    OPTIONAL_TESTS: "true"
  - nodejs_version: "6"
    REQUIRED_TESTS: "true"
  - nodejs_version: "6"
    OPTIONAL_TESTS: "true"

matrix:
  fast_finish: true
  allow_failures:
    - OPTIONAL_TESTS: true

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/2a667026696d38f78146
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

platform:
  - x64

test_script:
  - node -v
  - npm -v
  - npm test

build: off
skip_tags: true
